spring.application.name=hospitalManagement

server.port=8081 

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitaldb
spring.datasource.username=postgres
spring.datasource.password=Achyut@1235
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true 

